[package]
name = "mycp437generator"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl3 = { version = "0.17.3", features = ["ttf", "image"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1.0.101"
